apiVersion: v1
kind: Secret

metadata:
  name: targeting-secret
  namespace: toggle-mult

type: Opaque

stringData:
  DATABASE_URL: "postgres://postgres:postgres@postgres-db.cc9akw4u8gao.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=require"


