apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: sqs-auth
  namespace: toggle-mult

spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: sqs-secret
      key: AWS_ACCESS_KEY_ID

    - parameter: awsSecretAccessKey
      name: sqs-secret
      key: AWS_SECRET_ACCESS_KEY