apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  namespace: toggle-mult
data:
  POSTGRES_HOST: togglemaster-postgres.cc9akw4u8gao.us-east-1.rds.amazonaws.com
  POSTGRES_PORT: "5432"
  POSTGRES_DB: postgres
  
  