apiVersion: v1
kind: Secret 
metadata:
  name: auth-secret
  namespace: toggle-mult

type: Opaque

stringData:
  DATABASE_URL: postgres://postgres:postgres@togglemaster-postgres.cc9akw4u8gao.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=require
  MASTER_KEY: admin-secreto-123