apiVersion: v1
kind: ConfigMap

metadata:
  name: evaluation-configmap
  namespace: toggle-mult

data:

  PORT: "8004"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"

#Conexão com a fila SQS da AWS
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/050451396335/evaluation-service"
  AWS_REGION: "us-east-1"