apiVersion: apps/v1
kind: Deployment

metadata:
  name: evaluation-service
  namespace: toggle-mult

spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      serviceAccountName: evaluation-service-sa
      containers:
        - name: evaluation-service
          image: 050451396335.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:de8e882
          ports:
            - containerPort: 8004
          
          envFrom:
            - configMapRef:
                name: evaluation-configmap
            - secretRef:
                name: secret-evaluation

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "550m"
              memory: "950Mi"

          