apiVersion: v1
kind: Secret

metadata:
  name: secret-evaluation
  namespace: toggle-mult

type: Opaque

stringData:
  REDIS_URL: "rediss://togglemaster-redis.kq2l2w.ng.0001.use1.cache.amazonaws.com:6379"
  SERVICE_API_KEY: "tm_key_df565faa48e6bba779842a060f2dd65c0cc86f4362d318abd95ffce4a521fb9b"